#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

We recommend our Jammy baseimage instead:
https://github.com/linuxserver/docker-baseimage-ubuntu

See our Duplicati image for an example using mono:
https://github.com/linuxserver/docker-duplicati


******************************************************
******************************************************'
